### ISSUE TITLE
Web Youtube player issue with Playing to true on init

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#89]
We want the web player to start automatically if the currently joined room is already playing the song.
It works on the native version

**Comment by Devessier** [comment]
The issue was due to the fact that the Web player used to be unmounted when switched to full screen mode. It was broken and it could not play again until we play another video.
This issue has been resolved by https://github.com/AdonisEnProvence/MusicRoom/pull/85.
We can close it.

**Comment by prastoin** [comment]
Issue is still happening on a refresh.
We needed to wait for the user click as youtube player won't start if the tab is not focus

**Comment by Devessier** [comment]
Fixed by #81
